# Generated by Django 3.2.11 on 2022-01-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('sight', models.IntegerField(choices=[(0, 'Red'), (1, 'Green'), (2, 'Blue'), (3, 'Yellow'), (4, 'White'), (5, 'Black'), (6, 'Purple'), (7, 'Orange'), (8, 'Pink'), (9, 'Brown')])),
                ('touch', models.IntegerField(choices=[(0, 'Soft'), (1, 'Hard'), (2, 'Cool'), (3, 'Warm'), (4, 'Hot'), (5, 'Cold')])),
                ('taste', models.IntegerField(choices=[(0, 'Sweet'), (1, 'Salty'), (2, 'Bitter'), (3, 'Sour'), (4, 'Nutty'), (5, 'Hot')])),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
